version: '2.1'

services:
  backend-flask:
    build:
      context: ./backend-flask
    restart: always
    environment:
      PYTHONUNBUFFERED: 0
      REDIS_HOST: broker
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_SUBSCRIBE_CHANNEL: "multi-server"
    ports:
      - 5000:5000
    volumes:
      - ./backend-flask:/code
    depends_on:
      - broker

  backend-node:
    build:
      context: ./backend-node
    restart: always
    environment:
      REDIS_HOST: broker
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_SUBSCRIBE_CHANNEL: "multi-server"
      APP_ENV: development
    command: ["node", "server.js"]
    ports:
      - 8080:8080
    volumes:
      - ./backend-node:/code
    depends_on:
      - broker

  frontend:
    build:
      context: ./frontend
    restart: always
    command: npm run dev
    environment:
      HOST: '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/code

  broker:
    image: redis
    expose:
      - 6379
    ports:
      - 6379:6379

  db:
    image: mongo:3.7.3-jessie
    expose:
      - 27017
    ports:
      - 27017:27017
