source "https://rubygems.org"
gem 'redis', '~> 4.0', '>= 4.0.1'
gem 'sinatra', '~> 2.0', '>= 2.0.1'
gem 'sinatra-contrib', '~> 2.0', '>= 2.0.1'
gem 'sinatra-websocket', '~> 0.3.1'
gem 'sinatra-cross_origin', '~> 0.4.0'
